# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_wizard.ui'
#
# Created by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Wizard(object):
    def setupUi(self, Wizard):
        Wizard.setObjectName(_fromUtf8("Wizard"))
        Wizard.resize(328, 300)
        self.wizardPage1 = QtGui.QWizardPage()
        self.wizardPage1.setObjectName(_fromUtf8("wizardPage1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.wizardPage1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.labelInput = QtGui.QLabel(self.wizardPage1)
        self.labelInput.setObjectName(_fromUtf8("labelInput"))
        self.horizontalLayout_2.addWidget(self.labelInput)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.lineEditInput = QtGui.QLineEdit(self.wizardPage1)
        self.lineEditInput.setMinimumSize(QtCore.QSize(120, 0))
        self.lineEditInput.setObjectName(_fromUtf8("lineEditInput"))
        self.horizontalLayout_2.addWidget(self.lineEditInput)
        self.pushButtonInput = QtGui.QPushButton(self.wizardPage1)
        self.pushButtonInput.setObjectName(_fromUtf8("pushButtonInput"))
        self.horizontalLayout_2.addWidget(self.pushButtonInput)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(self.wizardPage1)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.lineEditOutput = QtGui.QLineEdit(self.wizardPage1)
        self.lineEditOutput.setMinimumSize(QtCore.QSize(120, 0))
        self.lineEditOutput.setText(_fromUtf8(""))
        self.lineEditOutput.setObjectName(_fromUtf8("lineEditOutput"))
        self.horizontalLayout.addWidget(self.lineEditOutput)
        self.pushButtonOutput = QtGui.QPushButton(self.wizardPage1)
        self.pushButtonOutput.setObjectName(_fromUtf8("pushButtonOutput"))
        self.horizontalLayout.addWidget(self.pushButtonOutput)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.labelControlProgram = QtGui.QLabel(self.wizardPage1)
        self.labelControlProgram.setObjectName(_fromUtf8("labelControlProgram"))
        self.horizontalLayout_3.addWidget(self.labelControlProgram)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.comboBoxModel = QtGui.QComboBox(self.wizardPage1)
        self.comboBoxModel.setMinimumSize(QtCore.QSize(120, 0))
        self.comboBoxModel.setObjectName(_fromUtf8("comboBoxModel"))
        self.comboBoxModel.addItem(_fromUtf8(""))
        self.comboBoxModel.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.comboBoxModel)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        Wizard.addPage(self.wizardPage1)
        self.wizardPage2 = QtGui.QWizardPage()
        self.wizardPage2.setObjectName(_fromUtf8("wizardPage2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.wizardPage2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.labelA = QtGui.QLabel(self.wizardPage2)
        self.labelA.setObjectName(_fromUtf8("labelA"))
        self.horizontalLayout_4.addWidget(self.labelA)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.comboBoxA = QtGui.QComboBox(self.wizardPage2)
        self.comboBoxA.setObjectName(_fromUtf8("comboBoxA"))
        self.comboBoxA.addItem(_fromUtf8(""))
        self.comboBoxA.addItem(_fromUtf8(""))
        self.comboBoxA.addItem(_fromUtf8(""))
        self.comboBoxA.addItem(_fromUtf8(""))
        self.comboBoxA.addItem(_fromUtf8(""))
        self.comboBoxA.addItem(_fromUtf8(""))
        self.comboBoxA.addItem(_fromUtf8(""))
        self.comboBoxA.addItem(_fromUtf8(""))
        self.comboBoxA.addItem(_fromUtf8(""))
        self.comboBoxA.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.comboBoxA)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.labelB = QtGui.QLabel(self.wizardPage2)
        self.labelB.setObjectName(_fromUtf8("labelB"))
        self.horizontalLayout_5.addWidget(self.labelB)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.comboBoxB = QtGui.QComboBox(self.wizardPage2)
        self.comboBoxB.setObjectName(_fromUtf8("comboBoxB"))
        self.comboBoxB.addItem(_fromUtf8(""))
        self.comboBoxB.addItem(_fromUtf8(""))
        self.comboBoxB.addItem(_fromUtf8(""))
        self.comboBoxB.addItem(_fromUtf8(""))
        self.comboBoxB.addItem(_fromUtf8(""))
        self.comboBoxB.addItem(_fromUtf8(""))
        self.comboBoxB.addItem(_fromUtf8(""))
        self.comboBoxB.addItem(_fromUtf8(""))
        self.comboBoxB.addItem(_fromUtf8(""))
        self.comboBoxB.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.comboBoxB)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.labelC = QtGui.QLabel(self.wizardPage2)
        self.labelC.setObjectName(_fromUtf8("labelC"))
        self.horizontalLayout_6.addWidget(self.labelC)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.comboBoxC = QtGui.QComboBox(self.wizardPage2)
        self.comboBoxC.setObjectName(_fromUtf8("comboBoxC"))
        self.comboBoxC.addItem(_fromUtf8(""))
        self.comboBoxC.addItem(_fromUtf8(""))
        self.comboBoxC.addItem(_fromUtf8(""))
        self.comboBoxC.addItem(_fromUtf8(""))
        self.comboBoxC.addItem(_fromUtf8(""))
        self.comboBoxC.addItem(_fromUtf8(""))
        self.comboBoxC.addItem(_fromUtf8(""))
        self.comboBoxC.addItem(_fromUtf8(""))
        self.comboBoxC.addItem(_fromUtf8(""))
        self.comboBoxC.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.comboBoxC)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.labelD = QtGui.QLabel(self.wizardPage2)
        self.labelD.setObjectName(_fromUtf8("labelD"))
        self.horizontalLayout_7.addWidget(self.labelD)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.comboBoxD = QtGui.QComboBox(self.wizardPage2)
        self.comboBoxD.setObjectName(_fromUtf8("comboBoxD"))
        self.comboBoxD.addItem(_fromUtf8(""))
        self.comboBoxD.addItem(_fromUtf8(""))
        self.comboBoxD.addItem(_fromUtf8(""))
        self.comboBoxD.addItem(_fromUtf8(""))
        self.comboBoxD.addItem(_fromUtf8(""))
        self.comboBoxD.addItem(_fromUtf8(""))
        self.comboBoxD.addItem(_fromUtf8(""))
        self.comboBoxD.addItem(_fromUtf8(""))
        self.comboBoxD.addItem(_fromUtf8(""))
        self.comboBoxD.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.comboBoxD)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.labelE = QtGui.QLabel(self.wizardPage2)
        self.labelE.setObjectName(_fromUtf8("labelE"))
        self.horizontalLayout_8.addWidget(self.labelE)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.comboBoxE = QtGui.QComboBox(self.wizardPage2)
        self.comboBoxE.setObjectName(_fromUtf8("comboBoxE"))
        self.comboBoxE.addItem(_fromUtf8(""))
        self.comboBoxE.addItem(_fromUtf8(""))
        self.comboBoxE.addItem(_fromUtf8(""))
        self.comboBoxE.addItem(_fromUtf8(""))
        self.comboBoxE.addItem(_fromUtf8(""))
        self.comboBoxE.addItem(_fromUtf8(""))
        self.comboBoxE.addItem(_fromUtf8(""))
        self.comboBoxE.addItem(_fromUtf8(""))
        self.comboBoxE.addItem(_fromUtf8(""))
        self.comboBoxE.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.comboBoxE)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.labelF = QtGui.QLabel(self.wizardPage2)
        self.labelF.setObjectName(_fromUtf8("labelF"))
        self.horizontalLayout_9.addWidget(self.labelF)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.comboBoxF = QtGui.QComboBox(self.wizardPage2)
        self.comboBoxF.setObjectName(_fromUtf8("comboBoxF"))
        self.comboBoxF.addItem(_fromUtf8(""))
        self.comboBoxF.addItem(_fromUtf8(""))
        self.comboBoxF.addItem(_fromUtf8(""))
        self.comboBoxF.addItem(_fromUtf8(""))
        self.comboBoxF.addItem(_fromUtf8(""))
        self.comboBoxF.addItem(_fromUtf8(""))
        self.comboBoxF.addItem(_fromUtf8(""))
        self.comboBoxF.addItem(_fromUtf8(""))
        self.comboBoxF.addItem(_fromUtf8(""))
        self.comboBoxF.addItem(_fromUtf8(""))
        self.horizontalLayout_9.addWidget(self.comboBoxF)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label = QtGui.QLabel(self.wizardPage2)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_10.addWidget(self.label)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.spinBoxTimeStep = QtGui.QSpinBox(self.wizardPage2)
        self.spinBoxTimeStep.setObjectName(_fromUtf8("spinBoxTimeStep"))
        self.horizontalLayout_10.addWidget(self.spinBoxTimeStep)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        Wizard.addPage(self.wizardPage2)

        self.retranslateUi(Wizard)
        QtCore.QMetaObject.connectSlotsByName(Wizard)

    def retranslateUi(self, Wizard):
        Wizard.setWindowTitle(_translate("Wizard", "Wizard", None))
        self.labelInput.setText(_translate("Wizard", "Input-File:", None))
        self.pushButtonInput.setText(_translate("Wizard", "Select", None))
        self.label_3.setText(_translate("Wizard", "Output-File:", None))
        self.pushButtonOutput.setText(_translate("Wizard", "Select", None))
        self.labelControlProgram.setText(_translate("Wizard", "Model:", None))
        self.comboBoxModel.setItemText(0, _translate("Wizard", "Model 3", None))
        self.comboBoxModel.setItemText(1, _translate("Wizard", "Model 4", None))
        self.labelA.setText(_translate("Wizard", "A", None))
        self.comboBoxA.setItemText(0, _translate("Wizard", "1", None))
        self.comboBoxA.setItemText(1, _translate("Wizard", "2", None))
        self.comboBoxA.setItemText(2, _translate("Wizard", "3", None))
        self.comboBoxA.setItemText(3, _translate("Wizard", "4", None))
        self.comboBoxA.setItemText(4, _translate("Wizard", "5", None))
        self.comboBoxA.setItemText(5, _translate("Wizard", "6", None))
        self.comboBoxA.setItemText(6, _translate("Wizard", "7", None))
        self.comboBoxA.setItemText(7, _translate("Wizard", "8", None))
        self.comboBoxA.setItemText(8, _translate("Wizard", "9", None))
        self.comboBoxA.setItemText(9, _translate("Wizard", "10", None))
        self.labelB.setText(_translate("Wizard", "B", None))
        self.comboBoxB.setItemText(0, _translate("Wizard", "1", None))
        self.comboBoxB.setItemText(1, _translate("Wizard", "2", None))
        self.comboBoxB.setItemText(2, _translate("Wizard", "3", None))
        self.comboBoxB.setItemText(3, _translate("Wizard", "4", None))
        self.comboBoxB.setItemText(4, _translate("Wizard", "5", None))
        self.comboBoxB.setItemText(5, _translate("Wizard", "6", None))
        self.comboBoxB.setItemText(6, _translate("Wizard", "7", None))
        self.comboBoxB.setItemText(7, _translate("Wizard", "8", None))
        self.comboBoxB.setItemText(8, _translate("Wizard", "9", None))
        self.comboBoxB.setItemText(9, _translate("Wizard", "10", None))
        self.labelC.setText(_translate("Wizard", "C", None))
        self.comboBoxC.setItemText(0, _translate("Wizard", "1", None))
        self.comboBoxC.setItemText(1, _translate("Wizard", "2", None))
        self.comboBoxC.setItemText(2, _translate("Wizard", "3", None))
        self.comboBoxC.setItemText(3, _translate("Wizard", "4", None))
        self.comboBoxC.setItemText(4, _translate("Wizard", "5", None))
        self.comboBoxC.setItemText(5, _translate("Wizard", "6", None))
        self.comboBoxC.setItemText(6, _translate("Wizard", "7", None))
        self.comboBoxC.setItemText(7, _translate("Wizard", "8", None))
        self.comboBoxC.setItemText(8, _translate("Wizard", "9", None))
        self.comboBoxC.setItemText(9, _translate("Wizard", "10", None))
        self.labelD.setText(_translate("Wizard", "D", None))
        self.comboBoxD.setItemText(0, _translate("Wizard", "1", None))
        self.comboBoxD.setItemText(1, _translate("Wizard", "2", None))
        self.comboBoxD.setItemText(2, _translate("Wizard", "3", None))
        self.comboBoxD.setItemText(3, _translate("Wizard", "4", None))
        self.comboBoxD.setItemText(4, _translate("Wizard", "5", None))
        self.comboBoxD.setItemText(5, _translate("Wizard", "6", None))
        self.comboBoxD.setItemText(6, _translate("Wizard", "7", None))
        self.comboBoxD.setItemText(7, _translate("Wizard", "8", None))
        self.comboBoxD.setItemText(8, _translate("Wizard", "9", None))
        self.comboBoxD.setItemText(9, _translate("Wizard", "10", None))
        self.labelE.setText(_translate("Wizard", "E", None))
        self.comboBoxE.setItemText(0, _translate("Wizard", "1", None))
        self.comboBoxE.setItemText(1, _translate("Wizard", "2", None))
        self.comboBoxE.setItemText(2, _translate("Wizard", "3", None))
        self.comboBoxE.setItemText(3, _translate("Wizard", "4", None))
        self.comboBoxE.setItemText(4, _translate("Wizard", "5", None))
        self.comboBoxE.setItemText(5, _translate("Wizard", "6", None))
        self.comboBoxE.setItemText(6, _translate("Wizard", "7", None))
        self.comboBoxE.setItemText(7, _translate("Wizard", "8", None))
        self.comboBoxE.setItemText(8, _translate("Wizard", "9", None))
        self.comboBoxE.setItemText(9, _translate("Wizard", "10", None))
        self.labelF.setText(_translate("Wizard", "F", None))
        self.comboBoxF.setItemText(0, _translate("Wizard", "1", None))
        self.comboBoxF.setItemText(1, _translate("Wizard", "2", None))
        self.comboBoxF.setItemText(2, _translate("Wizard", "3", None))
        self.comboBoxF.setItemText(3, _translate("Wizard", "4", None))
        self.comboBoxF.setItemText(4, _translate("Wizard", "5", None))
        self.comboBoxF.setItemText(5, _translate("Wizard", "6", None))
        self.comboBoxF.setItemText(6, _translate("Wizard", "7", None))
        self.comboBoxF.setItemText(7, _translate("Wizard", "8", None))
        self.comboBoxF.setItemText(8, _translate("Wizard", "9", None))
        self.comboBoxF.setItemText(9, _translate("Wizard", "10", None))
        self.label.setText(_translate("Wizard", "Time step (hours):", None))

