# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_wizard.ui'
#
# Created: Fri Dec  4 09:24:46 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Wizard(object):
    def setupUi(self, Wizard):
        Wizard.setObjectName(_fromUtf8("Wizard"))
        Wizard.resize(662, 386)
        Wizard.setWindowOpacity(1.0)
        self.wizardPage1 = QtGui.QWizardPage()
        self.wizardPage1.setObjectName(_fromUtf8("wizardPage1"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.wizardPage1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox = QtGui.QGroupBox(self.wizardPage1)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelInput = QtGui.QLabel(self.groupBox)
        self.labelInput.setObjectName(_fromUtf8("labelInput"))
        self.horizontalLayout.addWidget(self.labelInput)
        self.lineEditInputFileName = QtGui.QLineEdit(self.groupBox)
        self.lineEditInputFileName.setMinimumSize(QtCore.QSize(120, 0))
        self.lineEditInputFileName.setObjectName(_fromUtf8("lineEditInputFileName"))
        self.horizontalLayout.addWidget(self.lineEditInputFileName)
        self.pushButtonInput = QtGui.QPushButton(self.groupBox)
        self.pushButtonInput.setObjectName(_fromUtf8("pushButtonInput"))
        self.horizontalLayout.addWidget(self.pushButtonInput)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.wizardPage1)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.labelFileName = QtGui.QLabel(self.groupBox_2)
        self.labelFileName.setObjectName(_fromUtf8("labelFileName"))
        self.verticalLayout_3.addWidget(self.labelFileName)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lineEditOutputFolder = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditOutputFolder.setMinimumSize(QtCore.QSize(120, 0))
        self.lineEditOutputFolder.setText(_fromUtf8(""))
        self.lineEditOutputFolder.setObjectName(_fromUtf8("lineEditOutputFolder"))
        self.horizontalLayout_2.addWidget(self.lineEditOutputFolder)
        self.pushButtonOutput = QtGui.QPushButton(self.groupBox_2)
        self.pushButtonOutput.setObjectName(_fromUtf8("pushButtonOutput"))
        self.horizontalLayout_2.addWidget(self.pushButtonOutput)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.lineEditOutputFileName = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditOutputFileName.setObjectName(_fromUtf8("lineEditOutputFileName"))
        self.verticalLayout.addWidget(self.lineEditOutputFileName)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.wizardPage1)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.labelControlProgram = QtGui.QLabel(self.groupBox_3)
        self.labelControlProgram.setObjectName(_fromUtf8("labelControlProgram"))
        self.horizontalLayout_11.addWidget(self.labelControlProgram)
        self.comboBoxModel = QtGui.QComboBox(self.groupBox_3)
        self.comboBoxModel.setMinimumSize(QtCore.QSize(120, 0))
        self.comboBoxModel.setObjectName(_fromUtf8("comboBoxModel"))
        self.comboBoxModel.addItem(_fromUtf8(""))
        self.comboBoxModel.addItem(_fromUtf8(""))
        self.horizontalLayout_11.addWidget(self.comboBoxModel)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        Wizard.addPage(self.wizardPage1)
        self.wizardPage2 = QtGui.QWizardPage()
        self.wizardPage2.setObjectName(_fromUtf8("wizardPage2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.wizardPage2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.labelA = QtGui.QLabel(self.wizardPage2)
        self.labelA.setToolTip(_fromUtf8(""))
        self.labelA.setObjectName(_fromUtf8("labelA"))
        self.horizontalLayout_4.addWidget(self.labelA)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.comboBoxA = QtGui.QComboBox(self.wizardPage2)
        self.comboBoxA.setObjectName(_fromUtf8("comboBoxA"))
        self.comboBoxA.addItem(_fromUtf8(""))
        self.comboBoxA.addItem(_fromUtf8(""))
        self.comboBoxA.addItem(_fromUtf8(""))
        self.comboBoxA.addItem(_fromUtf8(""))
        self.comboBoxA.addItem(_fromUtf8(""))
        self.comboBoxA.addItem(_fromUtf8(""))
        self.comboBoxA.addItem(_fromUtf8(""))
        self.comboBoxA.addItem(_fromUtf8(""))
        self.comboBoxA.addItem(_fromUtf8(""))
        self.comboBoxA.addItem(_fromUtf8(""))
        self.comboBoxA.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.comboBoxA)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.labelB = QtGui.QLabel(self.wizardPage2)
        self.labelB.setToolTip(_fromUtf8(""))
        self.labelB.setObjectName(_fromUtf8("labelB"))
        self.horizontalLayout_5.addWidget(self.labelB)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.comboBoxB = QtGui.QComboBox(self.wizardPage2)
        self.comboBoxB.setObjectName(_fromUtf8("comboBoxB"))
        self.comboBoxB.addItem(_fromUtf8(""))
        self.comboBoxB.addItem(_fromUtf8(""))
        self.comboBoxB.addItem(_fromUtf8(""))
        self.comboBoxB.addItem(_fromUtf8(""))
        self.comboBoxB.addItem(_fromUtf8(""))
        self.comboBoxB.addItem(_fromUtf8(""))
        self.comboBoxB.addItem(_fromUtf8(""))
        self.comboBoxB.addItem(_fromUtf8(""))
        self.comboBoxB.addItem(_fromUtf8(""))
        self.comboBoxB.addItem(_fromUtf8(""))
        self.comboBoxB.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.comboBoxB)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.labelC = QtGui.QLabel(self.wizardPage2)
        self.labelC.setToolTip(_fromUtf8(""))
        self.labelC.setObjectName(_fromUtf8("labelC"))
        self.horizontalLayout_6.addWidget(self.labelC)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.comboBoxC = QtGui.QComboBox(self.wizardPage2)
        self.comboBoxC.setObjectName(_fromUtf8("comboBoxC"))
        self.comboBoxC.addItem(_fromUtf8(""))
        self.comboBoxC.addItem(_fromUtf8(""))
        self.comboBoxC.addItem(_fromUtf8(""))
        self.comboBoxC.addItem(_fromUtf8(""))
        self.comboBoxC.addItem(_fromUtf8(""))
        self.comboBoxC.addItem(_fromUtf8(""))
        self.comboBoxC.addItem(_fromUtf8(""))
        self.comboBoxC.addItem(_fromUtf8(""))
        self.comboBoxC.addItem(_fromUtf8(""))
        self.comboBoxC.addItem(_fromUtf8(""))
        self.comboBoxC.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.comboBoxC)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.labelD = QtGui.QLabel(self.wizardPage2)
        self.labelD.setToolTip(_fromUtf8(""))
        self.labelD.setObjectName(_fromUtf8("labelD"))
        self.horizontalLayout_7.addWidget(self.labelD)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.comboBoxD = QtGui.QComboBox(self.wizardPage2)
        self.comboBoxD.setObjectName(_fromUtf8("comboBoxD"))
        self.comboBoxD.addItem(_fromUtf8(""))
        self.comboBoxD.addItem(_fromUtf8(""))
        self.comboBoxD.addItem(_fromUtf8(""))
        self.comboBoxD.addItem(_fromUtf8(""))
        self.comboBoxD.addItem(_fromUtf8(""))
        self.comboBoxD.addItem(_fromUtf8(""))
        self.comboBoxD.addItem(_fromUtf8(""))
        self.comboBoxD.addItem(_fromUtf8(""))
        self.comboBoxD.addItem(_fromUtf8(""))
        self.comboBoxD.addItem(_fromUtf8(""))
        self.comboBoxD.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.comboBoxD)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.labelE = QtGui.QLabel(self.wizardPage2)
        self.labelE.setObjectName(_fromUtf8("labelE"))
        self.horizontalLayout_8.addWidget(self.labelE)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.comboBoxE = QtGui.QComboBox(self.wizardPage2)
        self.comboBoxE.setObjectName(_fromUtf8("comboBoxE"))
        self.comboBoxE.addItem(_fromUtf8(""))
        self.comboBoxE.addItem(_fromUtf8(""))
        self.comboBoxE.addItem(_fromUtf8(""))
        self.comboBoxE.addItem(_fromUtf8(""))
        self.comboBoxE.addItem(_fromUtf8(""))
        self.comboBoxE.addItem(_fromUtf8(""))
        self.comboBoxE.addItem(_fromUtf8(""))
        self.comboBoxE.addItem(_fromUtf8(""))
        self.comboBoxE.addItem(_fromUtf8(""))
        self.comboBoxE.addItem(_fromUtf8(""))
        self.comboBoxE.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.comboBoxE)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.labelF = QtGui.QLabel(self.wizardPage2)
        self.labelF.setToolTip(_fromUtf8(""))
        self.labelF.setObjectName(_fromUtf8("labelF"))
        self.horizontalLayout_9.addWidget(self.labelF)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.comboBoxF = QtGui.QComboBox(self.wizardPage2)
        self.comboBoxF.setObjectName(_fromUtf8("comboBoxF"))
        self.comboBoxF.addItem(_fromUtf8(""))
        self.comboBoxF.addItem(_fromUtf8(""))
        self.comboBoxF.addItem(_fromUtf8(""))
        self.comboBoxF.addItem(_fromUtf8(""))
        self.comboBoxF.addItem(_fromUtf8(""))
        self.comboBoxF.addItem(_fromUtf8(""))
        self.comboBoxF.addItem(_fromUtf8(""))
        self.comboBoxF.addItem(_fromUtf8(""))
        self.comboBoxF.addItem(_fromUtf8(""))
        self.comboBoxF.addItem(_fromUtf8(""))
        self.comboBoxF.addItem(_fromUtf8(""))
        self.horizontalLayout_9.addWidget(self.comboBoxF)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label = QtGui.QLabel(self.wizardPage2)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_10.addWidget(self.label)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.spinBoxTimeStep = QtGui.QSpinBox(self.wizardPage2)
        self.spinBoxTimeStep.setProperty("value", 10)
        self.spinBoxTimeStep.setObjectName(_fromUtf8("spinBoxTimeStep"))
        self.horizontalLayout_10.addWidget(self.spinBoxTimeStep)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        Wizard.addPage(self.wizardPage2)

        self.retranslateUi(Wizard)
        QtCore.QMetaObject.connectSlotsByName(Wizard)

    def retranslateUi(self, Wizard):
        Wizard.setWindowTitle(_translate("Wizard", "STH prediction", None))
        self.groupBox.setTitle(_translate("Wizard", "Input", None))
        self.labelInput.setToolTip(_translate("Wizard", "Select the input shapefile", None))
        self.labelInput.setText(_translate("Wizard", "File-Name:", None))
        self.lineEditInputFileName.setToolTip(_translate("Wizard", "The chosen file name.", None))
        self.pushButtonInput.setToolTip(_translate("Wizard", "Select the input shapefile", None))
        self.pushButtonInput.setText(_translate("Wizard", "Select", None))
        self.groupBox_2.setTitle(_translate("Wizard", "Output", None))
        self.label_3.setToolTip(_translate("Wizard", "Choose a output folder to place the simulation results inside.", None))
        self.label_3.setText(_translate("Wizard", "Output-Folder: ", None))
        self.labelFileName.setToolTip(_translate("Wizard", "Set the name of the result file.", None))
        self.labelFileName.setText(_translate("Wizard", "File-Name:", None))
        self.lineEditOutputFolder.setToolTip(_translate("Wizard", "Location of the output folder.", None))
        self.pushButtonOutput.setToolTip(_translate("Wizard", "Select the output folder", None))
        self.pushButtonOutput.setText(_translate("Wizard", "Select", None))
        self.lineEditOutputFileName.setToolTip(_translate("Wizard", "your desired name of the output shapefile", None))
        self.groupBox_3.setTitle(_translate("Wizard", "Models", None))
        self.labelControlProgram.setToolTip(_translate("Wizard", "Select the model you would like to use. Model 3 uses... Model 4 uses...", None))
        self.labelControlProgram.setText(_translate("Wizard", "Select a model for simulation", None))
        self.comboBoxModel.setToolTip(_translate("Wizard", "<html><head/><body><p>Total prevalance is used when only total prevalances of the STH are known.</p><p>STH prevalance is used when intensities of the STH are known.</p></body></html>", None))
        self.comboBoxModel.setItemText(0, _translate("Wizard", "Total prevalance", None))
        self.comboBoxModel.setItemText(1, _translate("Wizard", "STH prevalance", None))
        self.labelA.setText(_translate("Wizard", "0%   <=  Total prevalance < 1%", None))
        self.comboBoxA.setToolTip(_translate("Wizard", "<html><head/><body><p><span style=\" color:#ff0000;\">CP stands for Control Program. Each CP refers to a strategy as a combination of type of drug and frequency of distribution.</span></p><p><span style=\" font-weight:600; text-decoration: underline; color:#ff0000;\">No Intervention is default when total prevalance &lt; 1%</span></p><p><br/>- CP1 refers to administration of anthelminthic (ALB) twice a year</p><p>- CP2 refers to administration of mebendazole (MEB) twice a year</p><p>- CP3 refers to administration of ALB once a year</p><p>- CP4 refers to administration of MEB once a year</p><p>- CP5 refers to administration of ALB in the context of lymphatic filariasis (LF) with 6 months interval</p><p>- CP6 refers to administration of ALB in the context of lymphatic filariasis (LF) + MEB with 6 months interval</p><p>- CP7 refers to administration of ALB in the context of lymphatic filariasis (LF) + DEC with 6 months interval</p><p>- CP8 refers to administration of ALB in the context of lymphatic filariasis (LF) + DEC with 6 months interval</p><p>- CP9 refers to administration of ALB in the context of lymphatic filariasis (LF) + DEC with one year interval</p><p>- CP10 refers to administration of ALB in the context of lymphatic filariasis (LF) + IVR with one year interval</p></body></html>", None))
        self.comboBoxA.setItemText(0, _translate("Wizard", "No intervention", None))
        self.comboBoxA.setItemText(1, _translate("Wizard", "CP1", None))
        self.comboBoxA.setItemText(2, _translate("Wizard", "CP2", None))
        self.comboBoxA.setItemText(3, _translate("Wizard", "CP3", None))
        self.comboBoxA.setItemText(4, _translate("Wizard", "CP4", None))
        self.comboBoxA.setItemText(5, _translate("Wizard", "CP5", None))
        self.comboBoxA.setItemText(6, _translate("Wizard", "CP6", None))
        self.comboBoxA.setItemText(7, _translate("Wizard", "CP7", None))
        self.comboBoxA.setItemText(8, _translate("Wizard", "CP8", None))
        self.comboBoxA.setItemText(9, _translate("Wizard", "CP9", None))
        self.comboBoxA.setItemText(10, _translate("Wizard", "CP10", None))
        self.labelB.setText(_translate("Wizard", "1%    <= Total prevalance < 10%", None))
        self.comboBoxB.setToolTip(_translate("Wizard", "<html><head/><body><p><span style=\" color:#ff0000;\">CP stands for Control Program. Each CP refers to a strategy as a combination of type of drug and frequency of distribution.</span></p><p><span style=\" font-weight:600; text-decoration: underline; color:#ff0000;\">No Intervention</span><span style=\" font-weight:600; text-decoration: underline; color:#ff0000;\"> is default when 1% &lt;= Total prevalance &lt; 10%</span><span style=\" color:#ff0000;\"><br/></span></p><p>- CP1 refers to administration of anthelminthic (ALB) twice a year</p><p>- CP2 refers to administration of mebendazole (MEB) twice a year</p><p>- CP3 refers to administration of ALB once a year</p><p>- CP4 refers to administration of MEB once a year</p><p>- CP5 refers to administration of ALB in the context of lymphatic filariasis (LF) with 6 months interval</p><p>- CP6 refers to administration of ALB in the context of lymphatic filariasis (LF) + MEB with 6 months interval</p><p>- CP7 refers to administration of ALB in the context of lymphatic filariasis (LF) + DEC with 6 months interval</p><p>- CP8 refers to administration of ALB in the context of lymphatic filariasis (LF) + DEC with 6 months interval</p><p>- CP9 refers to administration of ALB in the context of lymphatic filariasis (LF) + DEC with one year interval</p><p>- CP10 refers to administration of ALB in the context of lymphatic filariasis (LF) + IVR with one year interval</p></body></html>", None))
        self.comboBoxB.setItemText(0, _translate("Wizard", "No intervention", None))
        self.comboBoxB.setItemText(1, _translate("Wizard", "CP1", None))
        self.comboBoxB.setItemText(2, _translate("Wizard", "CP2", None))
        self.comboBoxB.setItemText(3, _translate("Wizard", "CP3", None))
        self.comboBoxB.setItemText(4, _translate("Wizard", "CP4", None))
        self.comboBoxB.setItemText(5, _translate("Wizard", "CP5", None))
        self.comboBoxB.setItemText(6, _translate("Wizard", "CP6", None))
        self.comboBoxB.setItemText(7, _translate("Wizard", "CP7", None))
        self.comboBoxB.setItemText(8, _translate("Wizard", "CP8", None))
        self.comboBoxB.setItemText(9, _translate("Wizard", "CP9", None))
        self.comboBoxB.setItemText(10, _translate("Wizard", "CP10", None))
        self.labelC.setText(_translate("Wizard", "10% <= Total prevalance < 20%", None))
        self.comboBoxC.setToolTip(_translate("Wizard", "<html><head/><body><p><span style=\" color:#ff0000;\">CP stands for Control Program. Each CP refers to a strategy as a combination of type of drug and frequency of distribution.</span></p><p><span style=\" font-weight:600; text-decoration: underline; color:#ff0000;\">No intervention is default when 10% &lt;= Total prevalance &lt; 20%</span></p><p><span style=\" color:#ff0000;\"><br/></span>- CP1 refers to administration of anthelminthic (ALB) twice a year</p><p>- CP2 refers to administration of mebendazole (MEB) twice a year</p><p>- CP3 refers to administration of ALB once a year</p><p>- CP4 refers to administration of MEB once a year</p><p>- CP5 refers to administration of ALB in the context of lymphatic filariasis (LF) with 6 months interval</p><p>- CP6 refers to administration of ALB in the context of lymphatic filariasis (LF) + MEB with 6 months interval</p><p>- CP7 refers to administration of ALB in the context of lymphatic filariasis (LF) + DEC with 6 months interval</p><p>- CP8 refers to administration of ALB in the context of lymphatic filariasis (LF) + DEC with 6 months interval</p><p>- CP9 refers to administration of ALB in the context of lymphatic filariasis (LF) + DEC with one year interval</p><p>- CP10 refers to administration of ALB in the context of lymphatic filariasis (LF) + IVR with one year interval</p></body></html>", None))
        self.comboBoxC.setItemText(0, _translate("Wizard", "No intervention", None))
        self.comboBoxC.setItemText(1, _translate("Wizard", "CP1", None))
        self.comboBoxC.setItemText(2, _translate("Wizard", "CP2", None))
        self.comboBoxC.setItemText(3, _translate("Wizard", "CP3", None))
        self.comboBoxC.setItemText(4, _translate("Wizard", "CP4", None))
        self.comboBoxC.setItemText(5, _translate("Wizard", "CP5", None))
        self.comboBoxC.setItemText(6, _translate("Wizard", "CP6", None))
        self.comboBoxC.setItemText(7, _translate("Wizard", "CP7", None))
        self.comboBoxC.setItemText(8, _translate("Wizard", "CP8", None))
        self.comboBoxC.setItemText(9, _translate("Wizard", "CP9", None))
        self.comboBoxC.setItemText(10, _translate("Wizard", "CP10", None))
        self.labelD.setText(_translate("Wizard", "20% <= Total prevalance < 50%", None))
        self.comboBoxD.setToolTip(_translate("Wizard", "<html><head/><body><p><span style=\" color:#ff0000;\">CP stands for Control Program. Each CP refers to a strategy as a combination of type of drug and frequency of distribution.</span></p><p><span style=\" font-weight:600; text-decoration: underline; color:#ff0000;\">CP3 is default when 20% &lt;= Total prevalance &lt; 50%</span></p><p><span style=\" color:#ff0000;\"><br/></span>- CP1 refers to administration of anthelminthic (ALB) twice a year</p><p>- CP2 refers to administration of mebendazole (MEB) twice a year</p><p>- CP3 refers to administration of ALB once a year</p><p>- CP4 refers to administration of MEB once a year</p><p>- CP5 refers to administration of ALB in the context of lymphatic filariasis (LF) with 6 months interval</p><p>- CP6 refers to administration of ALB in the context of lymphatic filariasis (LF) + MEB with 6 months interval</p><p>- CP7 refers to administration of ALB in the context of lymphatic filariasis (LF) + DEC with 6 months interval</p><p>- CP8 refers to administration of ALB in the context of lymphatic filariasis (LF) + DEC with 6 months interval</p><p>- CP9 refers to administration of ALB in the context of lymphatic filariasis (LF) + DEC with one year interval</p><p>- CP10 refers to administration of ALB in the context of lymphatic filariasis (LF) + IVR with one year interval</p></body></html>", None))
        self.comboBoxD.setItemText(0, _translate("Wizard", "CP3", None))
        self.comboBoxD.setItemText(1, _translate("Wizard", "CP1", None))
        self.comboBoxD.setItemText(2, _translate("Wizard", "CP2", None))
        self.comboBoxD.setItemText(3, _translate("Wizard", "CP4", None))
        self.comboBoxD.setItemText(4, _translate("Wizard", "CP5", None))
        self.comboBoxD.setItemText(5, _translate("Wizard", "CP6", None))
        self.comboBoxD.setItemText(6, _translate("Wizard", "CP7", None))
        self.comboBoxD.setItemText(7, _translate("Wizard", "CP8", None))
        self.comboBoxD.setItemText(8, _translate("Wizard", "CP9", None))
        self.comboBoxD.setItemText(9, _translate("Wizard", "CP10", None))
        self.comboBoxD.setItemText(10, _translate("Wizard", "No intervention", None))
        self.labelE.setText(_translate("Wizard", "50% <= Total prevalance < 70%", None))
        self.comboBoxE.setToolTip(_translate("Wizard", "<html><head/><body><p><span style=\" color:#ff0000;\">CP stands for Control Program. Each CP refers to a strategy as a combination of type of drug and frequency of distribution.</span></p><p><span style=\" font-weight:600; text-decoration: underline; color:#ff0000;\">CP1 is default when 50% &lt;= Total prevalance &lt; 70%</span><span style=\" color:#ff0000;\"><br/></span></p><p>- CP1 refers to administration of anthelminthic (ALB) twice a year</p><p>- CP2 refers to administration of mebendazole (MEB) twice a year</p><p>- CP3 refers to administration of ALB once a year</p><p>- CP4 refers to administration of MEB once a year</p><p>- CP5 refers to administration of ALB in the context of lymphatic filariasis (LF) with 6 months interval</p><p>- CP6 refers to administration of ALB in the context of lymphatic filariasis (LF) + MEB with 6 months interval</p><p>- CP7 refers to administration of ALB in the context of lymphatic filariasis (LF) + DEC with 6 months interval</p><p>- CP8 refers to administration of ALB in the context of lymphatic filariasis (LF) + DEC with 6 months interval</p><p>- CP9 refers to administration of ALB in the context of lymphatic filariasis (LF) + DEC with one year interval</p><p>- CP10 refers to administration of ALB in the context of lymphatic filariasis (LF) + IVR with one year interval</p></body></html>", None))
        self.comboBoxE.setItemText(0, _translate("Wizard", "CP1", None))
        self.comboBoxE.setItemText(1, _translate("Wizard", "CP2", None))
        self.comboBoxE.setItemText(2, _translate("Wizard", "CP3", None))
        self.comboBoxE.setItemText(3, _translate("Wizard", "CP4", None))
        self.comboBoxE.setItemText(4, _translate("Wizard", "CP5", None))
        self.comboBoxE.setItemText(5, _translate("Wizard", "CP6", None))
        self.comboBoxE.setItemText(6, _translate("Wizard", "CP7", None))
        self.comboBoxE.setItemText(7, _translate("Wizard", "CP8", None))
        self.comboBoxE.setItemText(8, _translate("Wizard", "CP9", None))
        self.comboBoxE.setItemText(9, _translate("Wizard", "CP10", None))
        self.comboBoxE.setItemText(10, _translate("Wizard", "No intervention", None))
        self.labelF.setText(_translate("Wizard", "70% <= Total prevalance <= 100%", None))
        self.comboBoxF.setToolTip(_translate("Wizard", "<html><head/><body><p><span style=\" color:#ff0000;\">CP stands for Control Program. Each CP refers to a strategy as a combination of type of drug and frequency of distribution.</span></p><p><span style=\" font-weight:600; text-decoration: underline; color:#ff0000;\">CP1 is default when 70% &lt;= Total prevalance &lt;= 100%</span><span style=\" color:#ff0000;\"><br/></span></p><p>- CP1 refers to administration of anthelminthic (ALB) twice a year</p><p>- CP2 refers to administration of mebendazole (MEB) twice a year</p><p>- CP3 refers to administration of ALB once a year</p><p>- CP4 refers to administration of MEB once a year</p><p>- CP5 refers to administration of ALB in the context of lymphatic filariasis (LF) with 6 months interval</p><p>- CP6 refers to administration of ALB in the context of lymphatic filariasis (LF) + MEB with 6 months interval</p><p>- CP7 refers to administration of ALB in the context of lymphatic filariasis (LF) + DEC with 6 months interval</p><p>- CP8 refers to administration of ALB in the context of lymphatic filariasis (LF) + DEC with 6 months interval</p><p>- CP9 refers to administration of ALB in the context of lymphatic filariasis (LF) + DEC with one year interval</p><p>- CP10 refers to administration of ALB in the context of lymphatic filariasis (LF) + IVR with one year interval</p></body></html>", None))
        self.comboBoxF.setItemText(0, _translate("Wizard", "CP1", None))
        self.comboBoxF.setItemText(1, _translate("Wizard", "CP2", None))
        self.comboBoxF.setItemText(2, _translate("Wizard", "CP3", None))
        self.comboBoxF.setItemText(3, _translate("Wizard", "CP4", None))
        self.comboBoxF.setItemText(4, _translate("Wizard", "CP5", None))
        self.comboBoxF.setItemText(5, _translate("Wizard", "CP6", None))
        self.comboBoxF.setItemText(6, _translate("Wizard", "CP7", None))
        self.comboBoxF.setItemText(7, _translate("Wizard", "CP8", None))
        self.comboBoxF.setItemText(8, _translate("Wizard", "CP9", None))
        self.comboBoxF.setItemText(9, _translate("Wizard", "CP10", None))
        self.comboBoxF.setItemText(10, _translate("Wizard", "No intervention", None))
        self.label.setText(_translate("Wizard", "Numbers of years used for prediction", None))
        self.spinBoxTimeStep.setToolTip(_translate("Wizard", "<html><head/><body><p>Enter here the numbers of years. </p><p>The defaul value is 10 years</p></body></html>", None))

